# Generated by Django 4.2.2 on 2023-11-03 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_school_name', models.CharField(max_length=500)),
                ('student_std', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='school_student',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_teacher',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=500)),
                ('school_t_name', models.CharField(max_length=500)),
                ('class_teacher', models.CharField(max_length=50)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.school')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.school'),
        ),
        migrations.CreateModel(
            name='clark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clark_name', models.CharField(max_length=500)),
                ('clark_position', models.CharField(max_length=500)),
                ('clark_school', models.CharField(max_length=500)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.school')),
            ],
        ),
    ]
