# Generated by Django 4.2.2 on 2023-11-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0002_student_school_school_student_school_school_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_student',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='stu',
        ),
        migrations.AddField(
            model_name='student',
            name='tch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crud.teacher'),
        ),
    ]
