# Generated by Django 4.2.2 on 2023-11-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0003_remove_school_school_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_Country',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_city',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_state',
        ),
        migrations.AddField(
            model_name='school',
            name='school_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='addrese_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_course',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_salary', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=500)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_fees', models.IntegerField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.student')),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=500)),
                ('bus_root', models.CharField(max_length=500)),
                ('school_bus', models.CharField(max_length=500)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crud.student')),
            ],
        ),
    ]
