# Generated by Django 4.2.2 on 2023-11-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0005_remove_bus_stu_student_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='stu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crud.student'),
        ),
    ]
