# Generated by Django 4.2.2 on 2023-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0006_remove_student_bus_bus_stu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='addrese_area',
        ),
        migrations.AddField(
            model_name='student',
            name='student_a_area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
