# Generated by Django 4.2.2 on 2023-11-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0007_remove_student_addrese_area_student_student_a_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='stu',
        ),
        migrations.AddField(
            model_name='student',
            name='Bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_crud.bus'),
        ),
    ]
